<?php

namespace Qcm\QcmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function byQuestion($idQuestion){
        $qb = $this->createQueryBuilder('q')
                    ->where('q.id = :idQuestion')
                    ->setParameter('idQuestion', $idQuestion);
        return $qb->getQuery()->getResult();
    }
	public function getListQuestionByCategories($idCategorie){
        $qb = $this->createQueryBuilder('q')
                    ->join('q.categorie', 'c')
                    ->where('c.nomCategorie = :idCategorie')
                    ->setParameter('idCategorie', $idCategorie);
        return $qb->getQuery()->getResult();
    }
    
    
}
