<?php

namespace Qcm\QcmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends EntityRepository
{
    public function byQuestion($idQuestion){
        $qb = $this->createQueryBuilder('r')
                    ->join('r.question', 'q')
                    ->where('q.id = :idQuestion')
                    ->setParameter('idQuestion', $idQuestion);
        return $qb->getQuery()->getResult();
    }
}
