<?php

namespace Qcm\QcmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReponseExacteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseExacteRepository extends EntityRepository
{
    public function byQuestionReponse($idQuestion){
        $qb = $this->createQueryBuilder('qr')
                    ->join('qr.question', 'q')
                    ->join('qr.reponse', 'r')
                    ->where('q.id = :idQuestion')
                    ->setParameter('idQuestion', $idQuestion);
        return $qb->getQuery()->getResult();
    }
}
