<?php

namespace Utilisateurs\UtilisateursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursRepository extends EntityRepository
{
    public function findOneByUsername($username){
        $qb = $this->createQueryBuilder('u')
                    ->where('u.username = :idQuestion')
                    ->setParameter('idQuestion', $username);
        return $qb->getQuery()->getResult();
    }
}