<?php

namespace Dex\DexBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserUtilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserUtilRepository extends EntityRepository
{
}
